name: 'Harrier Setup Action'
description: 'Test run of a Harrier setup action'
author: 'Harrier Team'
inputs:
  org:
    description: 'organization pulled from github context object'
    required: true
  repo:
    description: 'the repository name that the action is running in'
    required: true
  personal-access-token:
    description: "user secret pulled from organization's secrets"
    required: true
runs:
  using: 'node12' # should this match the emitted target JS version in the eventual JS code?
  main: 'index.js' # in the future... /dist/index.js
