name: "My First GitHub Action"
description: "A basic action that logs a message."
author: "Your Name"
inputs:
  example_input:
    description: "An example input parameter"
    required: false
    default: "Hello World"
  my-secret:
    description: "Secret pulled from client repo"
    required: true
  your-secret: 
    description: "repository_id pulled from github context object"
    required: true
  runner-os:
    description: "runner.os pulled from runner context object"
    required: true
  org:
    description: ""
    required: true
  joel-pat:
    decription: ""
    required: true
runs:
  using: "node12"
  main: "index.js"
