name: 'My First GitHub Action'
description: 'A basic action that logs a message.'
author: 'Your Name'
inputs:
  example_input:
    description: 'An example input parameter'
    required: false
    default: 'Hello World'
  my-secret:
    description: 'Secret pulled from client repo'
    required: true
  your-secret:
    description: 'repository_id pulled from github context object'
    required: true
  runner-os:
    description: 'runner.os pulled from runner context object'
    required: true
  org:
    description: 'organization pulled from github context object'
    required: true
  joel-pat:
    description: "user secret pulled from organization's secrets"
    required: true
runs:
  using: 'node12' # should this match the emitted target JS version in the eventual JS code?
  main: 'index.js' # in the future... /dist/index.js
